import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";

export const roboto = Roboto({
    subsets: ['latin'],
    variable: '--font-roboto', // Opcional: para usar como variável CSS
});
export const robotoMono = Roboto_Mono({
    subsets: ['latin'],
    variable: '--font-roboto-mono', // Opcional: para usar como variável CSS
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${roboto.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
